from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard-admin/', views.dashboard_admin, name='dashboard_admin'),
    path('dashboard-user/', views.dashboard_user, name='dashboard_user'),
    path('waiting-room/', views.waiting_room, name='waiting_room'),
    path('app/', views.app_home, name='app_home'),
    path('produits/', views.produit_list, name='produit_list'),
    path('produits/new/', views.produit_create, name='produit_create'),
    path('produits/<int:pk>/edit/', views.produit_edit, name='produit_edit'),
    path('produits/<int:pk>/delete/', views.produit_delete, name='produit_delete'),
   # path('users/', views.user_management, name='user_management'),
    path('users/<int:pk>/delete/', views.delete_user, name='delete_user'),
    path('bon-entrees/', views.bon_entree_list, name='bon_entree_list'),
    path('bon-entrees/new/', views.bon_entree_create, name='bon_entree_create'),
    path('bon-entrees/<int:pk>/', views.bon_entree_detail, name='bon_entree_detail'),
    path('bon-sorties/', views.bon_sortie_list, name='bon_sortie_list'),
    path('bon-sorties/new/', views.bon_sortie_create, name='bon_sortie_create'),
    path('bon-sorties/<int:pk>/', views.bon_sortie_detail, name='bon_sortie_detail'),
    path('clients/', views.client_list, name='client_list'),
    path('clients/new/', views.client_create, name='client_create'),
    path('clients/<int:pk>/edit/', views.client_edit, name='client_edit'),
    path('clients/<int:pk>/delete/', views.client_delete, name='client_delete'),
    path('fournisseurs/', views.fournisseur_list, name='fournisseur_list'),
    path('fournisseurs/new/', views.fournisseur_create, name='fournisseur_create'),
    path('fournisseurs/<int:pk>/edit/', views.fournisseur_edit, name='fournisseur_edit'),
    path('fournisseurs/<int:pk>/delete/', views.fournisseur_delete, name='fournisseur_delete'),
    # path('entreprises/', views.entreprise_list, name='entreprise_list'),
    # path('entreprises/new/', views.entreprise_create, name='entreprise_create'),
    # path('entreprises/<int:pk>/edit/', views.entreprise_edit, name='entreprise_edit'),
    # path('entreprises/<int:pk>/delete/', views.entreprise_delete, name='entreprise_delete'),
    path('data-dashboard/', views.data_dashboard, name='data_dashboard'),
    path('api/produits/', views.produit_api, name='produit_api'),
    path('api/produits/<int:pk>/', views.produit_api_detail, name='produit_api_detail'),
  path('api/notifications/<int:product_id>/read/', views.notification_mark_read, name='notification_mark_read'),
path('api/notifications/<int:product_id>/delete/', views.notification_mark_deleted, name='notification_mark_deleted'),
path('bon-entrees/<int:pk>/delete/', views.bon_entree_delete, name='bon_entree_delete'),
path('bon-sorties/<int:pk>/delete/', views.bon_sortie_delete, name='bon_sortie_delete'),
path('users/', views.user_list, name='user_list'),
path('users/create/', views.user_create, name='user_create'),
path('users/<int:pk>/edit/', views.user_edit, name='user_edit'),
path('users/<int:pk>/delete/', views.delete_user, name='delete_user'),
path('produits/<int:pk>/history/', views.produit_history, name='produit_history'),
path('clients/<int:pk>/history/', views.client_history, name='client_history'),
path('fournisseurs/<int:pk>/history/', views.fournisseur_history, name='fournisseur_history'),
path('users/<str:username>/history/', views.user_history, name='user_history'),
path('admin-report/', views.admin_report, name='admin_report'),

]
