# Generated by Django 6.0.3 on 2026-04-28 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('code_cl', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('num_f', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('code_p', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('qte_stock', models.IntegerField(default=0)),
                ('stock_alerte', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='BonSortie',
            fields=[
                ('num_s', models.AutoField(primary_key=True, serialize=False)),
                ('date_s', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.client')),
            ],
        ),
        migrations.CreateModel(
            name='BonEntree',
            fields=[
                ('num_e', models.AutoField(primary_key=True, serialize=False)),
                ('date_e', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='LigneSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_s', models.IntegerField()),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='inventory.bonsortie')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LigneEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_e', models.IntegerField()),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='inventory.bonentree')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('staff', 'Staff'), ('user', 'Utilisateur')], default='user', max_length=20)),
                ('must_change_password', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('ban_until', models.DateTimeField(blank=True, null=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('otp_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('otp_enabled', models.BooleanField(default=False)),
                ('reset_password_token', models.CharField(blank=True, max_length=100, null=True)),
                ('reset_token_expires', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bonsortie',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.utilisateur'),
        ),
        migrations.AddField(
            model_name='bonentree',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.utilisateur'),
        ),
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.utilisateur')),
            ],
            options={
                'unique_together': {('utilisateur', 'produit')},
            },
        ),
    ]
