# Generated by Django 6.0.4 on 2026-04-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('email_request', "Demande de changement d'email"), ('email_approved', "Changement d'email approuvé"), ('email_rejected', "Changement d'email refusé"), ('email_confirmed', 'Email confirmé'), ('stock_alert', 'Alerte stock faible'), ('password_change', 'Changement de mot de passe')], max_length=50),
        ),
    ]
