# Generated by Django 6.0.3 on 2026-04-29 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_utilisateur_email_change_request_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email_request', "Demande de changement d'email"), ('email_approved', "Changement d'email approuvé"), ('email_rejected', "Changement d'email refusé"), ('email_confirmed', 'Email confirmé'), ('stock_alert', 'Alerte stock faible')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.utilisateur')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
