# Generated by Django 6.0.4 on 2026-04-16 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_notificationstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneentree',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_entree', to='inventory.produit'),
        ),
        migrations.AlterField(
            model_name='lignesortie',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_sortie', to='inventory.produit'),
        ),
    ]
