# Generated by Django 6.0.3 on 2026-04-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='pending_email_new',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='pending_email_otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='pending_email_otp_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='pending_email_otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
