# Generated by Django 6.0.4 on 2026-04-16 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_ligneentree_produit_alter_lignesortie_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonentree',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_entree', to='inventory.fournisseur'),
        ),
        migrations.AlterField(
            model_name='bonsortie',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_sortie', to='inventory.client'),
        ),
    ]
