# Generated by Django 6.0.3 on 2026-04-29 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_utilisateur_pending_email_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='pending_email_otp_secret',
        ),
    ]
